### ISSUE TITLE
REGgae Music Package

### ISSUE THREAD

**Issue by MRuzzante** [MRuzzante/Jah-referencing#2]
- [x] List songs and quotes on Google Sheet
- [x] Create playlist in Spotify and YouTube so users can see all the songs available in the package and contribute
- [x] Write program which randomly picks one of these songs and displays quote and link to the video in Stata

**Comment by JulieBousquet** [comment]
Man, ETA ? @MRuzzante

**Comment by MRuzzante** [comment]
A preliminary version (with 15 songs and no options) will be internally circulated by the end of the day. Please test and provide feedback on bugs and potential improvements.

**Comment by MRuzzante** [comment]
Awaiting feedback from slacking rastas @jonasguthoff and @JulieBousquet :unamused:

**Comment by MRuzzante** [comment]
Please use Issue #4 to suggest new options

**Comment by MRuzzante** [comment]
The package is now live! :metal:
